-- Generated by scripts/generate-dashboard-config-sql.js
-- Run via Supabase SQL editor or: supabase db execute -f config/dashboard_config_updates.sql

-- Update VC Studio Investor Default
UPDATE workspace_dashboard_configurations
SET dashboard_config = '{"role_configurations":{"investor":{"menu_items":[{"label":"Portfolio","component_id":"vc_pyramid","position":1,"is_default":true,"icon":"trending-up"},{"label":"Documents","component_id":"file_explorer","position":2,"icon":"folder"},{"label":"Workflows","component_id":"workflow_tasks","position":3,"icon":"list-checks"}],"dashboard_name":"Portfolio","workspace_layout":{"sidebar_width":"250px","theme":"light","show_notifications":true,"default_component":"vc_pyramid","menu_style":"ring","menu_style_mobile":"burger"},"widgets":[]},"administrator":{"menu_items":[{"label":"Portfolio","component_id":"vc_pyramid","position":1,"is_default":true,"icon":"trending-up"},{"label":"Documents","component_id":"file_explorer","position":2,"icon":"folder"},{"label":"Workflows","component_id":"workflow_tasks","position":3,"icon":"list-checks"}],"dashboard_name":"Portfolio","workspace_layout":{"sidebar_width":"250px","theme":"light","show_notifications":true,"default_component":"vc_pyramid","menu_style":"ring","menu_style_mobile":"burger"},"widgets":[]}}}'::jsonb
WHERE config_name = 'VC Studio Investor Default';

-- Update VC Studio Administrator Default
UPDATE workspace_dashboard_configurations
SET dashboard_config = '{"role_configurations":{"administrator":{"menu_items":[{"label":"File Manager","component_id":"file_explorer","position":1,"is_default":true,"icon":"folder"},{"label":"Workflows","component_id":"workflow_tasks","position":2,"icon":"list-checks"},{"label":"Settings","component_id":"workspace_settings","position":3,"icon":"settings"}],"dashboard_name":"Administrator Dashboard","workspace_layout":{"sidebar_width":"280px","theme":"light","show_notifications":true,"default_component":"file_explorer","menu_style":"ring","menu_style_mobile":"burger"},"widgets":[]}}}'::jsonb
WHERE config_name = 'VC Studio Administrator Default';

-- Update VC Studio Individual Default
UPDATE workspace_dashboard_configurations
SET dashboard_config = '{"role_configurations":{"individual":{"menu_items":[{"label":"My Files","component_id":"file_explorer","position":1,"is_default":true,"icon":"folder"},{"label":"Tasks","component_id":"workflow_tasks","position":2,"icon":"list-checks"}],"dashboard_name":"My Workspace","workspace_layout":{"sidebar_width":"250px","theme":"light","show_notifications":true,"default_component":"file_explorer","menu_style":"ring","menu_style_mobile":"burger"},"widgets":[]}}}'::jsonb
WHERE config_name = 'VC Studio Individual Default';
